### ISSUE TITLE
Unable to create a registrable event.

### ISSUE THREAD

**Issue by lukereative** [symbiote-library/silverstripe-eventmanagement#15]
I get an error when trying to create a registrable event (as a child of a calendar) - I am using a fresh SS3.1 (stable) install and database. The error log that I get is:

```
[error] [client ::1] PHP Fatal error:  Couldn't run query: \nSELECT DISTINCT count(DISTINCT "EventRegistration"."ID") AS "0"\nFROM "EventRegistration"\nWHERE ("ParentID" = '9') AND ("EventRegistration"."Status" = 'Valid') \n\nUnknown column 'ParentID' in 'where clause' in /Users/Luke/Sites/test/framework/model/MySQLDatabase.php on line 592, referer: http://localhost/test/admin/pages/edit/show/9
```

I am able to create normal events fine though.

**Comment by Reinkaos** [comment]
Adding this template fixed a similar issue for me, is there any content that is supposed to go in the template?

**Comment by philbenoit** [comment]
@Reinkaos I am not to sure, I have moved on from the project and do not have access to the code any more. I think I created a basic button in there with an action back to the controller.

**Comment by lukereative** [comment]
Closing this as I assume it was fixed by https://github.com/symbiote-library/silverstripe-eventmanagement/commit/d84a095637c56dd32491ad598c40c5663d532b5f
